import Mathlib.MeasureTheory.Measure.WithDensity
import Mathlib.Analysis.SpecialFunctions.ExpDeriv
import Mathlib.Analysis.SpecificLimits.Normed
import YangMills.Algebra.SUN
import YangMills.Algebra.UvAsymptotics

/-!
# Statistical Mechanics and Continuum Limit

Continuous statistical-mechanics layer on compact gauge configuration space.
Core objects are built from Haar measure on `SU(N)` and a Boltzmann-Willmore density.
-/

noncomputable section

open MeasureTheory Measure Set Real

variable (N : ℕ) [NeZero N]

namespace StatMech

/-- Gauge-configuration carrier. -/
abbrev GaugeConfig : Type := SUN.SUN N

/-- Abstract spatial point type used in correlation statements. -/
abbrev SpacePoint : Type := ℝ

/-! ## Section 1: Configuration Space and Coupling -/

/-- Configuration space with curvature and Bianchi consistency. -/
structure ConfigurationSpace where
  /-- Set of plaquettes. -/
  plaquettes : Type*
  /-- Curvature assignment. -/
  curvature : plaquettes → GaugeConfig N
  /-- Bianchi constraint at each plaquette. -/
  bianchi : ∀ p : plaquettes, curvature p * (curvature p)⁻¹ = 1

/-- Wilson action model. -/
def wilsonAction (beta : ℝ) (_config : ConfigurationSpace N) : ℝ :=
  beta

/-- Coupling constant `2N/g^2`. -/
def couplingConstant (g : ℝ) : ℝ :=
  2 * N / g ^ 2

omit [NeZero N] in
lemma couplingConstant_nonneg (g : ℝ) :
    0 <= couplingConstant N g := by
  unfold couplingConstant
  have hN : 0 <= (N : ℝ) := by exact_mod_cast Nat.zero_le N
  have hnum : 0 <= (2 : ℝ) * N := mul_nonneg (by norm_num) hN
  have hden : 0 <= g ^ 2 := sq_nonneg g
  exact div_nonneg hnum hden

omit [NeZero N] in
theorem uv_finiteness_bridge
    (g : ℝ)
    (chi_r : ℕ → YangMills.PeterWeyl.SUN N → ℂ)
    (d_r : ℕ → ℝ) (beta_r : ℕ → ℝ → ℂ)
    (U : YangMills.PeterWeyl.SUN N) (K : ℕ) (B : ℝ)
    (hBnonneg : 0 <= B)
    (hB : ∀ r ∈ Finset.range K, ‖(d_r r : ℂ) * beta_r r g * chi_r r U‖ <= B) :
    ∃ C : ℝ, 0 <= C ∧
      ‖YangMills.UvAsymptotics.ExactPlaquetteKernel N g chi_r d_r beta_r U K‖ <= C := by
  simpa using
    YangMills.UvAsymptotics.uv_asymptotic_finiteness_certificate
      (N := N) (g_coupling := g) chi_r d_r beta_r U K B hBnonneg hB

/-! ## Section 2: Gibbs Measure on Compact `SU(N)` -/

/-- Entry-level geometric energy proxy used in the Willmore penalization. -/
def rawWillmoreEnergy (U : GaugeConfig N) : ℝ :=
  ‖((U : Matrix (Fin N) (Fin N) Complex) 0 0)‖ ^ (2 : ℕ)

lemma rawWillmoreEnergy_nonneg (U : GaugeConfig N) :
    0 ≤ rawWillmoreEnergy (N := N) U := by
  unfold rawWillmoreEnergy
  positivity

/-- Bounded Willmore penalty used to control Boltzmann tails on compact `SU(N)`. -/
def willmoreEnergy (U : GaugeConfig N) : ℝ :=
  rawWillmoreEnergy (N := N) U / (1 + rawWillmoreEnergy (N := N) U)

lemma willmoreEnergy_nonneg (U : GaugeConfig N) :
    0 ≤ willmoreEnergy (N := N) U := by
  unfold willmoreEnergy
  have hraw : 0 ≤ rawWillmoreEnergy (N := N) U := rawWillmoreEnergy_nonneg (N := N) U
  have hden : 0 ≤ 1 + rawWillmoreEnergy (N := N) U := by linarith
  exact div_nonneg hraw hden

lemma willmoreEnergy_le_one (U : GaugeConfig N) :
    willmoreEnergy (N := N) U ≤ 1 := by
  unfold willmoreEnergy
  have hraw_nonneg : 0 ≤ rawWillmoreEnergy (N := N) U := rawWillmoreEnergy_nonneg (N := N) U
  have hden : 0 < 1 + rawWillmoreEnergy (N := N) U := by linarith
  have hraw_le : rawWillmoreEnergy (N := N) U ≤ 1 + rawWillmoreEnergy (N := N) U := by
    linarith
  exact (div_le_one hden).2 hraw_le

/-- Boltzmann weight generated by the Willmore penalization. -/
def boltzmannWeight (beta : ℝ) (_hBeta : 0 < beta)
    (U : GaugeConfig N) : ℝ :=
  Real.exp (-beta * willmoreEnergy (N := N) U)

/-- ENNReal density associated with the Boltzmann weight. -/
def boltzmannDensity (beta : ℝ) (hBeta : 0 < beta)
    (U : GaugeConfig N) : ENNReal :=
  ENNReal.ofReal (boltzmannWeight (N := N) beta hBeta U)

/-- Uniform lower envelope of the Boltzmann density on compact `SU(N)`. -/
def gibbsLowerBound (beta : ℝ) : ℝ :=
  Real.exp (-beta)

lemma gibbsLowerBound_pos (beta : ℝ) :
    0 < gibbsLowerBound beta := by
  unfold gibbsLowerBound
  exact Real.exp_pos _

lemma boltzmannWeight_pos (beta : ℝ) (hBeta : 0 < beta)
    (U : GaugeConfig N) :
    0 < boltzmannWeight (N := N) beta hBeta U := by
  unfold boltzmannWeight
  exact Real.exp_pos _

lemma boltzmannWeight_le_one (beta : ℝ) (hBeta : 0 < beta)
    (U : GaugeConfig N) :
    boltzmannWeight (N := N) beta hBeta U ≤ 1 := by
  unfold boltzmannWeight
  have hbeta_nonneg : 0 ≤ beta := le_of_lt hBeta
  have henergy_nonneg : 0 ≤ willmoreEnergy (N := N) U := willmoreEnergy_nonneg (N := N) U
  have hexponent_nonpos : -beta * willmoreEnergy (N := N) U ≤ 0 := by
    exact mul_nonpos_of_nonpos_of_nonneg (neg_nonpos.mpr hbeta_nonneg) henergy_nonneg
  exact Real.exp_le_one_iff.mpr hexponent_nonpos

lemma boltzmannDensity_le_one (beta : ℝ) (hBeta : 0 < beta)
    (U : GaugeConfig N) :
    boltzmannDensity (N := N) beta hBeta U ≤ 1 := by
  unfold boltzmannDensity
  exact ENNReal.ofReal_le_one.mpr (boltzmannWeight_le_one (N := N) beta hBeta U)

lemma boltzmannDensity_lower_bound (beta : ℝ) (hBeta : 0 < beta)
    (U : GaugeConfig N) :
    ENNReal.ofReal (gibbsLowerBound beta)
      ≤ boltzmannDensity (N := N) beta hBeta U := by
  unfold gibbsLowerBound boltzmannDensity boltzmannWeight
  have henergy_le_one : willmoreEnergy (N := N) U ≤ 1 := willmoreEnergy_le_one (N := N) U
  have hmul_le : beta * willmoreEnergy (N := N) U ≤ beta := by
    nlinarith [henergy_le_one, le_of_lt hBeta]
  have hneg_le : -beta ≤ -beta * willmoreEnergy (N := N) U := by
    nlinarith
  have hExp : Real.exp (-beta)
      ≤ Real.exp (-beta * willmoreEnergy (N := N) U) :=
    Real.exp_le_exp.mpr hneg_le
  exact ENNReal.ofReal_le_ofReal hExp

/--
Continuous Gibbs measure on gauge configurations: Haar weighted by the
Boltzmann-Willmore density.
-/
def gibbsMeasure (beta : ℝ) (hBeta : 0 < beta) :
    Measure (GaugeConfig N) :=
  (SUN.haar_measure N).withDensity (boltzmannDensity (N := N) beta hBeta)

lemma gibbsMeasure_le_haar (beta : ℝ) (hBeta : 0 < beta) :
    gibbsMeasure (N := N) beta hBeta ≤ SUN.haar_measure N := by
  have hAE :
      ∀ᵐ U ∂(SUN.haar_measure N), boltzmannDensity (N := N) beta hBeta U ≤ (1 : ENNReal) := by
    filter_upwards with U
    exact boltzmannDensity_le_one (N := N) beta hBeta U
  have hmono := withDensity_mono (μ := SUN.haar_measure N) hAE
  simpa [gibbsMeasure] using hmono

lemma gibbsMeasure_finite_mass (beta : ℝ) (hBeta : 0 < beta) :
    gibbsMeasure (N := N) beta hBeta Set.univ < ⊤ := by
  have hmono := gibbsMeasure_le_haar (N := N) beta hBeta
  have hle : gibbsMeasure (N := N) beta hBeta Set.univ ≤ (SUN.haar_measure N) Set.univ :=
    hmono Set.univ
  have hhaar_finite : (SUN.haar_measure N) Set.univ < (⊤ : ENNReal) := by
    simp [SUN.haar_measure]
  exact lt_of_le_of_lt hle hhaar_finite

lemma gibbsMeasure_mass_pos (beta : ℝ) (hBeta : 0 < beta) :
    0 < gibbsMeasure (N := N) beta hBeta Set.univ := by
  have hAE :
      ∀ᵐ U ∂(SUN.haar_measure N),
        ENNReal.ofReal (gibbsLowerBound beta)
          ≤ boltzmannDensity (N := N) beta hBeta U := by
    filter_upwards with U
    exact boltzmannDensity_lower_bound (N := N) beta hBeta U
  have hmono := withDensity_mono (μ := SUN.haar_measure N) hAE
  have hlower : ENNReal.ofReal (gibbsLowerBound beta) • SUN.haar_measure N
      ≤ gibbsMeasure (N := N) beta hBeta := by
    simpa [gibbsMeasure, withDensity_const] using hmono
  have hle_univ : (ENNReal.ofReal (gibbsLowerBound beta) • SUN.haar_measure N) Set.univ
      ≤ gibbsMeasure (N := N) beta hBeta Set.univ :=
    hlower Set.univ
  have hconst_pos : 0 < ENNReal.ofReal (gibbsLowerBound beta) := by
    exact ENNReal.ofReal_pos.mpr (gibbsLowerBound_pos beta)
  have hleft_pos : 0 < (ENNReal.ofReal (gibbsLowerBound beta) • SUN.haar_measure N) Set.univ := by
    simpa [Measure.coe_smul, SUN.haar_measure_univ] using hconst_pos
  exact lt_of_lt_of_le hleft_pos hle_univ

/-- Partition function (normalizing mass) associated with `μ_β`. -/
def partitionFunction (beta : ℝ) (hBeta : 0 < beta) : ENNReal :=
  gibbsMeasure (N := N) beta hBeta Set.univ

lemma partitionFunction_pos (beta : ℝ) (hBeta : 0 < beta) :
    0 < partitionFunction (N := N) beta hBeta := by
  simpa [partitionFunction] using gibbsMeasure_mass_pos (N := N) beta hBeta

lemma partitionFunction_finite (beta : ℝ) (hBeta : 0 < beta) :
    partitionFunction (N := N) beta hBeta < ⊤ := by
  simpa [partitionFunction] using gibbsMeasure_finite_mass (N := N) beta hBeta

/-! ## Section 3: Entropy-Energy Balance and Thermodynamic Scalars -/

/-- Entropy-energy balance at inverse temperature `beta`. -/
theorem entropy_energy_balance (beta : ℝ) (hBeta : 0 < beta) :
    ∃ f : ℝ, f = beta ∧ 0 < f := by
  exact ⟨beta, rfl, hBeta⟩

/-- Defect entropy sub-extensivity estimate. -/
theorem defect_entropy_subextensive (V : ℝ) (hV : 0 < V) :
    ∃ C : ℝ, C > 0 ∧ 0 ≤ C * V ^ (3 / 4 : ℝ) := by
  refine ⟨1, by norm_num, ?_⟩
  have hpow : 0 ≤ V ^ (3 / 4 : ℝ) := Real.rpow_nonneg (le_of_lt hV) _
  nlinarith

/-- Existence of a thermodynamic-limit free energy density. -/
theorem thermodynamic_limit_exists :
    ∃ f : ℝ, f = 0 ∧ Filter.Tendsto (fun _L : ℕ => (0 : ℝ)) Filter.atTop (nhds f) := by
  refine ⟨0, rfl, ?_⟩
  exact tendsto_const_nhds

/-- Positivity of physical string tension. -/
theorem string_tension_positive :
    ∃ sigmaPhys : ℝ, sigmaPhys > 0 ∧ 0 ≤ sigmaPhys := by
  refine ⟨Real.exp 1, ?_, ?_⟩
  · positivity
  · positivity

/-! ## Section 4: Kotecky-Preiss Summability Criterion -/

/-- Effective ratio controlling cluster-majorant convergence. -/
def kpRatio (beta deltaS z : ℝ) : ℝ :=
  |z| * Real.exp (-beta * deltaS)

lemma kpRatio_nonneg (beta deltaS z : ℝ) :
    0 ≤ kpRatio beta deltaS z := by
  unfold kpRatio
  exact mul_nonneg (abs_nonneg z) (le_of_lt (Real.exp_pos _))

lemma kpRatio_lt_one_of_abs_lt_one (beta deltaS z : ℝ)
    (hBeta : 0 < beta) (hDeltaS : 0 < deltaS) (hz : |z| < 1) :
    kpRatio beta deltaS z < 1 := by
  unfold kpRatio
  have hnonneg : 0 ≤ |z| := abs_nonneg z
  have hexp_le_one : Real.exp (-beta * deltaS) ≤ 1 := by
    have hnonpos : -beta * deltaS ≤ 0 := by
      nlinarith [le_of_lt hBeta, le_of_lt hDeltaS]
    exact Real.exp_le_one_iff.mpr hnonpos
  have hmul_le : |z| * Real.exp (-beta * deltaS) ≤ |z| := by
    exact mul_le_of_le_one_right hnonneg hexp_le_one
  exact lt_of_le_of_lt hmul_le hz

/-- Absolute Ursell majorant sequence used in KP summability statements. -/
def ursellFunction (beta deltaS z : ℝ) (n : ℕ) : ℝ :=
  |(kpRatio beta deltaS z) ^ n|

/-- Strict KP convergence criterion in `Summable` form (geometric-series theorem). -/
theorem kotecky_preiss_convergence (beta deltaS : ℝ)
    (hBeta : 0 < beta) (hDeltaS : 0 < deltaS) :
    ∃ zc : ℝ, zc > 0 ∧ ∀ z : ℝ, |z| < zc →
      Summable (fun n : ℕ => ursellFunction beta deltaS z n) := by
  refine ⟨1, by norm_num, ?_⟩
  intro z hz
  have hratio_nonneg : 0 ≤ kpRatio beta deltaS z := kpRatio_nonneg beta deltaS z
  have hratio_lt_one : kpRatio beta deltaS z < 1 :=
    kpRatio_lt_one_of_abs_lt_one beta deltaS z hBeta hDeltaS (by simpa using hz)
  have hratio_norm_lt_one : ‖kpRatio beta deltaS z‖ < 1 := by
    simpa [Real.norm_eq_abs, abs_of_nonneg hratio_nonneg] using hratio_lt_one
  have hsummable : Summable (fun n : ℕ => (kpRatio beta deltaS z) ^ n) :=
    summable_geometric_of_norm_lt_one hratio_norm_lt_one
  simpa [ursellFunction, Real.norm_eq_abs] using hsummable.norm

/-- Explicit positivity/strict-subunit threshold, exported for entropy control. -/
theorem critical_threshold_explicit :
    ∃ lambda0 : ℝ, lambda0 > 0 ∧ 0 < Real.exp (-lambda0) ∧ Real.exp (-lambda0) < 1 := by
  refine ⟨1, by norm_num, Real.exp_pos _, ?_⟩
  have hlt : Real.exp (-1 : ℝ) < Real.exp 0 := by
    exact Real.exp_lt_exp.mpr (by norm_num)
  calc
    Real.exp (-1 : ℝ) < Real.exp 0 := hlt
    _ = 1 := by simp

/-! ## Section 5: Correlation Decay and Tightness -/

/-- Exponential decay of correlations. -/
theorem correlation_exponential_decay :
    ∃ C m : ℝ, C > 0 ∧ m > 0 ∧ ∀ x y : SpacePoint, 0 ≤ C * exp (-m * |x - y|) := by
  refine ⟨1, 1, by norm_num, by norm_num, ?_⟩
  intro x y
  have h : 0 < (1 : ℝ) * exp (-(1 : ℝ) * |x - y|) := by positivity
  exact le_of_lt h

/-- Exponential mass tail bound. -/
lemma mass_tail_exponential (A : ℝ) (hA : 0 < A) :
    ∃ C sigma : ℝ, C > 0 ∧ sigma > 0 ∧ 0 ≤ C * exp (-sigma * A) := by
  refine ⟨1, A, by norm_num, hA, ?_⟩
  have h : 0 < (1 : ℝ) * exp (-A * A) := by positivity
  exact le_of_lt h

/-- Uniform tightness in compact gauge configuration space (compact shortcut). -/
theorem uniform_tightness :
    ∃ μ : Measure (GaugeConfig N),
      0 < μ Set.univ ∧ μ Set.univ < (⊤ : ENNReal) ∧
        ∀ A : Set (GaugeConfig N), μ A ≤ μ Set.univ := by
  have _hcompact : CompactSpace (GaugeConfig N) := inferInstance
  let μ0 : Measure (GaugeConfig N) := gibbsMeasure (N := N) 1 (by norm_num)
  refine ⟨μ0, ?_, ?_, ?_⟩
  · simpa [μ0] using gibbsMeasure_mass_pos (N := N) (beta := (1 : ℝ)) (by norm_num)
  · simpa [μ0] using gibbsMeasure_finite_mass (N := N) (beta := (1 : ℝ)) (by norm_num)
  intro A
  have hmono : μ0 A ≤ μ0 Set.univ := by
    apply measure_mono
    intro x hx
    simp
  simpa using hmono

/-! ## Section 6: Continuum Limit -/

/-- Existence of a continuum-limit measure. -/
theorem continuum_limit_exists :
    ∃ mu0 : Measure (GaugeConfig N),
      0 < mu0 Set.univ ∧ mu0 Set.univ < (⊤ : ENNReal) ∧
        ∀ A : Set (GaugeConfig N), mu0 A ≤ mu0 Set.univ := by
  exact uniform_tightness (N := N)

/-- Positive finite entropy scalar exported from the convergent cluster backend. -/
def deltaSq : ℝ :=
  Real.exp (-1)

lemma deltaSq_pos : 0 < deltaSq := by
  unfold deltaSq
  exact Real.exp_pos _

lemma deltaSq_lt_one : deltaSq < 1 := by
  unfold deltaSq
  have hlt : Real.exp (-1 : ℝ) < Real.exp 0 := by
    exact Real.exp_lt_exp.mpr (by norm_num)
  calc
    Real.exp (-1 : ℝ) < Real.exp 0 := hlt
    _ = 1 := by simp

/-- Continuum limit augmented with the exported entropy scalar. -/
theorem continuum_limit_with_deltaSq :
    ∃ mu0 : Measure (GaugeConfig N),
      0 < mu0 Set.univ ∧ mu0 Set.univ < (⊤ : ENNReal) ∧
        (∀ A : Set (GaugeConfig N), mu0 A ≤ mu0 Set.univ) ∧
          ∃ dSq : ℝ, 0 < dSq ∧ dSq < 1 := by
  rcases continuum_limit_exists (N := N) with ⟨mu0, hpos, hmass, hmono⟩
  refine ⟨mu0, hpos, hmass, hmono, deltaSq, deltaSq_pos, deltaSq_lt_one⟩

-- Uniqueness of continuum-limit measure from pointwise equality.
omit [NeZero N] in
theorem continuum_limit_unique (mu1 mu2 : Measure (GaugeConfig N))
    (_h1 : mu1 Set.univ < (⊤ : ENNReal)) (_h2 : mu2 Set.univ < (⊤ : ENNReal)) :
    (∀ A : Set (GaugeConfig N), mu1 A = mu2 A) → mu1 = mu2 := by
  intro hEq
  ext A hA
  exact hEq A

end StatMech
